

version: 2.1


orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
  #   docker:
  #     - image: circleci/laravel

  #  working_directory: ~/repo

  #  steps:
  #  - run:
  #  - run: 
    executor:
      name: win/default
      size: "medium" # can be "medium", "large", "xlarge", "2xlarge"
    steps:
      - run: Write-Host 'Hello, Windows' 